# GenerateEmojiResources.ps1
#
# Scans Images\Twemoji\*.png and writes the @Ahk2Exe-AddResource directives
# into SupportFiles\EmojiResources.ahk.
#
# Run this script once after downloading Twemoji PNG files into Images\Twemoji\.
# The output file is then compiled into the .exe by Ahk2Exe.
#
# Usage (from any shell in the repo root or SupportFiles folder):
#   powershell -ExecutionPolicy Bypass -File SupportFiles\GenerateEmojiResources.ps1

$scriptDir  = Split-Path -Parent $MyInvocation.MyCommand.Path
$twemojiDir = Join-Path $scriptDir "Images\Twemoji"
$outputFile = Join-Path $scriptDir "EmojiResources.ahk"

if( -not (Test-Path $twemojiDir) )
{
    Write-Error "Twemoji folder not found: $twemojiDir"
    Write-Error "Create the folder and download PNG files from:"
    Write-Error "  https://github.com/jdecked/twemoji  (assets/72x72/)"
    exit 1
}

$pngFiles = Get-ChildItem -Path $twemojiDir -Filter "*.png" | Sort-Object Name

if( $pngFiles.Count -eq 0 )
{
    Write-Warning "No PNG files found in: $twemojiDir"
    Write-Warning "Download Twemoji 72x72 PNGs and place them there, then re-run."
    exit 0
}

$lines = [System.Collections.Generic.List[string]]::new()

$lines.Add("; EmojiResources.ahk - Auto-generated Ahk2Exe resource directives for Twemoji images.")
$lines.Add(";")
$lines.Add("; Generated by: SupportFiles\GenerateEmojiResources.ps1")
$lines.Add("; Generated on: $(Get-Date -Format 'yyyy-MM-dd HH:mm')")
$lines.Add("; PNG count:    $($pngFiles.Count)")
$lines.Add(";")
$lines.Add("; DO NOT EDIT BY HAND — re-run GenerateEmojiResources.ps1 instead.")
$lines.Add("")

foreach( $file in $pngFiles )
{
    $stem    = [System.IO.Path]::GetFileNameWithoutExtension($file.Name)
    $relPath = "Images\Twemoji\$($file.Name)"
    $lines.Add(";@Ahk2Exe-AddResource $relPath, E$stem")
}

[System.IO.File]::WriteAllLines( $outputFile,
                                 $lines,
                                 [System.Text.UTF8Encoding]::new($true) )

Write-Host "Written $($pngFiles.Count) resource directives to:"
Write-Host "  $outputFile"
