; Face Emojis
; Each emoji is registered as a symbol button on the "Emojis" tab.
; Layout: 4 rows, going down then across.

EMOJIS_TAB := 2
SetTabName( EMOJIS_TAB, "Emojis" )


RegisterSymbol( 1,  1, EMOJIS_TAB, "😀", "Grinning Face",                               ":grin:"         )
RegisterSymbol( 1,  2, EMOJIS_TAB, "😁", "Beaming Face",                                ":beaming:"      )
RegisterSymbol( 1,  3, EMOJIS_TAB, "😂", "Face with Tears of Joy",                      ":joy:"          )
RegisterSymbol( 1,  4, EMOJIS_TAB, "🤣", "Rolling on the Floor Laughing",               ":rofl:"         )
RegisterSymbol( 1,  5, EMOJIS_TAB, "😃", "Smiling Face with Open Mouth",                ":smiley:"       )
RegisterSymbol( 1,  6, EMOJIS_TAB, "😄", "Smiling Face with Open Mouth & Smiling Eyes", ":smile:"        )
RegisterSymbol( 1,  7, EMOJIS_TAB, "😅", "Smiling Face with Sweat",                     ":sweat_smile:"  )
RegisterSymbol( 1,  8, EMOJIS_TAB, "😆", "Smiling Face with Closed Eyes",               ":laughing:"     )
RegisterSymbol( 1,  9, EMOJIS_TAB, "😉", "Winking Face",                                ":wink:"         )
RegisterSymbol( 1, 10, EMOJIS_TAB, "😊", "Smiling Face with Smiling Eyes",              ":blush:"        )
RegisterSymbol( 1, 11, EMOJIS_TAB, "😋", "Face Savoring Food",                          ":yum:"          )
RegisterSymbol( 1, 12, EMOJIS_TAB, "😎", "Smiling Face with Sunglasses",                ":sunglasses:"   )

RegisterSymbol( 2,  1,  EMOJIS_TAB, "😍", "Heart Eyes",                     ":heart_eyes:"            )
RegisterSymbol( 2,  2,  EMOJIS_TAB, "😘", "Face Blowing a Kiss",            ":kissing_heart:"         )
RegisterSymbol( 2,  3,  EMOJIS_TAB, "😗", "Kissing Face",                   ":kissing:"               )
RegisterSymbol( 2,  4,  EMOJIS_TAB, "😙", "Kissing Face with Smiling Eyes", ":kissing_smiling_eyes:"  )
RegisterSymbol( 2,  5,  EMOJIS_TAB, "😚", "Kissing Face with Closed Eyes",  ":kissing_closed_eyes:"   )
RegisterSymbol( 2,  6,  EMOJIS_TAB, "🙂", "Slightly Smiling Face",          ":slightly_smiling:"      )
RegisterSymbol( 2,  7,  EMOJIS_TAB, "🤗", "Hugging Face",                   ":hugging:"               )
RegisterSymbol( 2,  8,  EMOJIS_TAB, "🤩", "Star-Struck",                    ":star_struck:"           )
RegisterSymbol( 2,  9,  EMOJIS_TAB, "🥰", "Smiling Face with Hearts",       ":smiling_hearts:"        )
RegisterSymbol( 2, 10,  EMOJIS_TAB, "😇", "Smiling Face with Halo",         ":innocent:"              )
RegisterSymbol( 2, 11,  EMOJIS_TAB, "🥲", "Smiling Face with Tear",         ":smiling_tear:"          )
RegisterSymbol( 2, 12,  EMOJIS_TAB, "😏", "Smirking Face",                  ":smirk:"                 )

RegisterSymbol( 3,  1,  EMOJIS_TAB, "😒", "Unamused Face",          ":unamused:"           )
RegisterSymbol( 3,  2,  EMOJIS_TAB, "😞", "Disappointed Face",      ":disappointed:"       )
RegisterSymbol( 3,  3,  EMOJIS_TAB, "😔", "Pensive Face",           ":pensive:"            )
RegisterSymbol( 3,  4,  EMOJIS_TAB, "😟", "Worried Face",           ":worried:"            )
RegisterSymbol( 3,  5,  EMOJIS_TAB, "😕", "Confused Face",          ":confused:"           )
RegisterSymbol( 3,  6,  EMOJIS_TAB, "🙁", "Slightly Frowning Face", ":slightly_frowning:"  )
RegisterSymbol( 3,  7,  EMOJIS_TAB, "☹️", "Frowning Face",          ":frowning:"           )
RegisterSymbol( 3,  8,  EMOJIS_TAB, "😣", "Persevering Face",       ":persevering:"        )
RegisterSymbol( 3,  9,  EMOJIS_TAB, "😖", "Confounded Face",        ":confounded:"         )
RegisterSymbol( 3, 10,  EMOJIS_TAB, "😫", "Tired Face",             ":tired:"              )
RegisterSymbol( 3, 11,  EMOJIS_TAB, "😩", "Weary Face",             ":weary:"              )
RegisterSymbol( 3, 12,  EMOJIS_TAB, "🥺", "Pleading Face",          ":pleading:"           )

RegisterSymbol( 4,  1,  EMOJIS_TAB, "😭", "Loudly Crying Face",         ":cry:"         )
RegisterSymbol( 4,  2,  EMOJIS_TAB, "😤", "Face with Steam From Nose",  ":face_steam:"  )
RegisterSymbol( 4,  3,  EMOJIS_TAB, "😠", "Angry Face",                 ":angry:"       )
RegisterSymbol( 4,  4,  EMOJIS_TAB, "😡", "Pouting Face",               ":pout:"        )
RegisterSymbol( 4,  5,  EMOJIS_TAB, "🤬", "Face with Symbols on Mouth", ":cursing:"     )
RegisterSymbol( 4,  6,  EMOJIS_TAB, "😳", "Flushed Face",               ":flushed:"     )
RegisterSymbol( 4,  7,  EMOJIS_TAB, "🥵", "Hot Face",                   ":hot:"         )
RegisterSymbol( 4,  8,  EMOJIS_TAB, "🥶", "Cold Face",                  ":cold:"        )
RegisterSymbol( 4,  9,  EMOJIS_TAB, "😱", "Face Screaming in Fear",     ":scream:"      )
RegisterSymbol( 4, 10,  EMOJIS_TAB, "😨", "Fearful Face",               ":fearful:"     )
RegisterSymbol( 4, 11,  EMOJIS_TAB, "😰", "Anxious Face with Sweat",    ":anxious:"     )
RegisterSymbol( 4, 12,  EMOJIS_TAB, "😥", "Sad but Relieved Face",      ":sad_relief:"  )

RegisterSymbol( 5,  1,  EMOJIS_TAB, "😓", "Downcast Face with Sweat",  ":downcast_sweat:"  )
RegisterSymbol( 5,  2,  EMOJIS_TAB, "🤔", "Thinking Face",             ":thinking:"        )
RegisterSymbol( 5,  3,  EMOJIS_TAB, "🤭", "Face with Hand Over Mouth", ":hand_over_mouth:" )
RegisterSymbol( 5,  4,  EMOJIS_TAB, "🤫", "Shushing Face",             ":shushing:"        )
RegisterSymbol( 5,  5,  EMOJIS_TAB, "🤥", "Lying Face",                ":lying:"           )
RegisterSymbol( 5,  6,  EMOJIS_TAB, "😶", "Face Without Mouth",        ":no_mouth:"        )
RegisterSymbol( 5,  7,  EMOJIS_TAB, "😐", "Neutral Face",              ":neutral:"         )
RegisterSymbol( 5,  8,  EMOJIS_TAB, "😬", "Grimacing Face",            ":grimacing:"       )
RegisterSymbol( 5,  9,  EMOJIS_TAB, "🙄", "Face with Rolling Eyes",    ":rolling_eyes:"    )
RegisterSymbol( 5, 10,  EMOJIS_TAB, "😯", "Hushed Face",               ":hushed:"          )
RegisterSymbol( 5, 11,  EMOJIS_TAB, "😴", "Sleeping Face",             ":sleeping:"        )
RegisterSymbol( 5, 12,  EMOJIS_TAB, "😪", "Sleepy Face",               ":sleepy:"          )
