; Emojis - organized by standard Unicode category
; Layout: row-primary, 12 columns.


class EmojisTabPage extends TabPage
{
  __New()
  {
    super.__New( "Emojis" )

    super.m_fontSize    := "s28"
    super.m_fontName    := "Segoe UI Emoji"
    super.m_symBtnSizeX := 50
    super.m_symBtnSizeY := 50

    super.SetRowsOf( 12 )
    this .RegisterButtons()
    super.RecalcSizes()
  }

  ; Insert a visual gap between categories.
  CategoryGap()
  {
    super.NextLine( true )
    super.ShiftLineByHalf()
  }

  RegisterButtons()
  {
    this.RegisterSmileys()
    this.CategoryGap()

    this.RegisterHeartsAndEmotion()
    this.CategoryGap()

    this.RegisterGestures()
    this.CategoryGap()

    this.RegisterPeople()
    this.CategoryGap()

    this.RegisterAnimals()
    this.CategoryGap()

    this.RegisterPlantsAndNature()
    this.CategoryGap()

    this.RegisterFoodAndDrink()
    this.CategoryGap()

    this.RegisterTravelAndPlaces()
    this.CategoryGap()

    this.RegisterActivities()
    this.CategoryGap()

    this.RegisterObjects()
    this.CategoryGap()

    this.RegisterSymbols()
  }

  ; ─── Smileys & Emotion — Faces ─────────────────────────────────
  RegisterSmileys()
  {
    super.RegisterSymbolX( 1, "😀", "Grinning Face`n:grin:"                                )
    super.RegisterSymbolX( 1, "😁", "Beaming Face`n:beaming:"                              )
    super.RegisterSymbolX( 1, "😂", "Face with Tears of Joy`n:joy:"                        )
    super.RegisterSymbolX( 1, "🤣", "Rolling on the Floor Laughing`n:rofl:"                )
    super.RegisterSymbolX( 1, "😃", "Smiling Face with Open Mouth`n:smiley:"               )
    super.RegisterSymbolX( 1, "😄", "Smiling Face with Smiling Eyes`n:smile:"              )
    super.RegisterSymbolX( 1, "😅", "Smiling Face with Sweat`n:sweat_smile:"               )
    super.RegisterSymbolX( 1, "😆", "Smiling Face with Closed Eyes`n:laughing:"            )
    super.RegisterSymbolX( 1, "😉", "Winking Face`n:wink:"                                 )
    super.RegisterSymbolX( 1, "😊", "Smiling Face with Smiling Eyes`n:blush:"              )
    super.RegisterSymbolX( 1, "😋", "Face Savoring Food`n:yum:"                            )
    super.RegisterSymbolX( 1, "😎", "Smiling Face with Sunglasses`n:sunglasses:"           )

    super.RegisterSymbolX( 1, "😍", "Heart Eyes`n:heart_eyes:"                               )
    super.RegisterSymbolX( 1, "😘", "Face Blowing a Kiss`n:kissing_heart:"                   )
    super.RegisterSymbolX( 1, "😗", "Kissing Face`n:kissing:"                                )
    super.RegisterSymbolX( 1, "😙", "Kissing Face with Smiling Eyes`n:kissing_smiling_eyes:" )
    super.RegisterSymbolX( 1, "😚", "Kissing Face with Closed Eyes`n:kissing_closed_eyes:"   )
    super.RegisterSymbolX( 1, "🙂", "Slightly Smiling Face`n:slightly_smiling:"              )
    super.RegisterSymbolX( 1, "🤗", "Hugging Face`n:hugging:"                                )
    super.RegisterSymbolX( 1, "🤩", "Star-Struck`n:star_struck:"                             )
    super.RegisterSymbolX( 1, "🥰", "Smiling Face with Hearts`n:smiling_hearts:"             )
    super.RegisterSymbolX( 1, "😇", "Smiling Face with Halo`n:innocent:"                     )
    super.RegisterSymbolX( 1, "🥲", "Smiling Face with Tear`n:smiling_tear:"                 )
    super.RegisterSymbolX( 1, "🤭", "Face with Hand over Mouth`n:hand_over_mouth:"           )

    super.RegisterSymbolX( 1, "🤫", "Shushing Face`n:shushing:"                    )
    super.RegisterSymbolX( 1, "🤔", "Thinking Face`n:thinking:"                    )
    super.RegisterSymbolX( 1, "🤐", "Zipper-Mouth Face`n:zipper_mouth:"            )
    super.RegisterSymbolX( 1, "🤨", "Face with Raised Eyebrow`n:raised_eyebrow:"   )
    super.RegisterSymbolX( 1, "😐", "Neutral Face`n:neutral_face:"                 )
    super.RegisterSymbolX( 1, "😑", "Expressionless Face`n:expressionless:"        )
    super.RegisterSymbolX( 1, "😶", "Face without Mouth`n:no_mouth:"               )
    super.RegisterSymbolX( 1, "😏", "Smirking Face`n:smirk:"                       )
    super.RegisterSymbolX( 1, "😒", "Unamused Face`n:unamused:"                    )
    super.RegisterSymbolX( 1, "🙄", "Face with Rolling Eyes`n:rolling_eyes:"       )
    super.RegisterSymbolX( 1, "😬", "Grimacing Face`n:grimacing:"                  )
    super.RegisterSymbolX( 1, "🤥", "Lying Face`n:lying:"                          )

    super.RegisterSymbolX( 1, "😌", "Relieved Face`n:relieved:"                )
    super.RegisterSymbolX( 1, "😔", "Pensive Face`n:pensive:"                  )
    super.RegisterSymbolX( 1, "😪", "Sleepy Face`n:sleepy:"                    )
    super.RegisterSymbolX( 1, "🤤", "Drooling Face`n:drooling:"                )
    super.RegisterSymbolX( 1, "😴", "Sleeping Face`n:sleeping:"                )
    super.RegisterSymbolX( 1, "🥱", "Yawning Face`n:yawning:"                  )
    super.RegisterSymbolX( 1, "😷", "Face with Medical Mask`n:mask:"           )
    super.RegisterSymbolX( 1, "🤒", "Face with Thermometer`n:thermometer:"     )
    super.RegisterSymbolX( 1, "🤕", "Face with Head Bandage`n:head_bandage:"   )
    super.RegisterSymbolX( 1, "🤢", "Nauseated Face`n:nauseated:"              )
    super.RegisterSymbolX( 1, "🤮", "Face Vomiting`n:vomiting:"                )
    super.RegisterSymbolX( 1, "🤧", "Sneezing Face`n:sneezing:"                )

    super.RegisterSymbolX( 1, "🥵", "Hot Face`n:hot:"                          )
    super.RegisterSymbolX( 1, "🥶", "Cold Face`n:cold:"                        )
    super.RegisterSymbolX( 1, "🥴", "Woozy Face`n:woozy:"                      )
    super.RegisterSymbolX( 1, "😵", "Dizzy Face`n:dizzy_face:"                 )
    super.RegisterSymbolX( 1, "🤯", "Exploding Head`n:exploding_head:"         )
    super.RegisterSymbolX( 1, "🤠", "Cowboy Hat Face`n:cowboy:"                )
    super.RegisterSymbolX( 1, "🥳", "Partying Face`n:partying:"                )
    super.RegisterSymbolX( 1, "🥸", "Disguised Face`n:disguised:"              )
    super.RegisterSymbolX( 1, "🤓", "Nerd Face`n:nerd:"                        )
    super.RegisterSymbolX( 1, "🧐", "Face with Monocle`n:monocle:"             )
    super.RegisterSymbolX( 1, "😎", "Smiling with Sunglasses`n:sunglasses2:"   )
    super.RegisterSymbolX( 1, "🥹", "Face Holding Back Tears`n:holding_tears:" )

    super.RegisterSymbolX( 1, "😕", "Confused Face`n:confused:"                    )
    super.RegisterSymbolX( 1, "😟", "Worried Face`n:worried:"                      )
    super.RegisterSymbolX( 1, "🙁", "Slightly Frowning Face`n:slightly_frowning:"  )
    super.RegisterSymbolX( 1, "☹️", "Frowning Face`n:frowning:"                    )
    super.RegisterSymbolX( 1, "😮", "Face with Open Mouth`n:open_mouth:"           )
    super.RegisterSymbolX( 1, "😯", "Hushed Face`n:hushed:"                        )
    super.RegisterSymbolX( 1, "😲", "Astonished Face`n:astonished:"               )
    super.RegisterSymbolX( 1, "😳", "Flushed Face`n:flushed:"                      )
    super.RegisterSymbolX( 1, "🥺", "Pleading Face`n:pleading:"                    )
    super.RegisterSymbolX( 1, "😦", "Frowning Open Mouth`n:frowning_open:"         )
    super.RegisterSymbolX( 1, "😧", "Anguished Face`n:anguished:"                  )
    super.RegisterSymbolX( 1, "😨", "Fearful Face`n:fearful:"                      )

    super.RegisterSymbolX( 1, "😰", "Anxious Face with Sweat`n:cold_sweat:"    )
    super.RegisterSymbolX( 1, "😥", "Sad but Relieved`n:disappointed_relieved:" )
    super.RegisterSymbolX( 1, "😢", "Crying Face`n:cry:"                        )
    super.RegisterSymbolX( 1, "😭", "Loudly Crying Face`n:sob:"                 )
    super.RegisterSymbolX( 1, "😱", "Screaming in Fear`n:scream:"               )
    super.RegisterSymbolX( 1, "😖", "Confounded Face`n:confounded:"             )
    super.RegisterSymbolX( 1, "😣", "Persevering Face`n:persevering:"           )
    super.RegisterSymbolX( 1, "😞", "Disappointed Face`n:disappointed:"         )
    super.RegisterSymbolX( 1, "😓", "Downcast with Sweat`n:sweat:"              )
    super.RegisterSymbolX( 1, "😩", "Weary Face`n:weary:"                       )
    super.RegisterSymbolX( 1, "😫", "Tired Face`n:tired_face:"                  )
    super.RegisterSymbolX( 1, "😤", "Face with Steam from Nose`n:triumph:"      )

    super.RegisterSymbolX( 1, "😡", "Pouting Face`n:rage:"                              )
    super.RegisterSymbolX( 1, "😠", "Angry Face`n:angry:"                               )
    super.RegisterSymbolX( 1, "🤬", "Face with Symbols on Mouth`n:symbols_on_mouth:"    )
    super.RegisterSymbolX( 1, "😈", "Smiling Face with Horns`n:smiling_imp:"            )
    super.RegisterSymbolX( 1, "👿", "Angry Face with Horns`n:imp:"                      )
    super.RegisterSymbolX( 1, "💀", "Skull`n:skull:"                                     )
    super.RegisterSymbolX( 1, "☠️", "Skull and Crossbones`n:skull_crossbones:"          )
    super.RegisterSymbolX( 1, "💩", "Pile of Poo`n:poop:"                               )
    super.RegisterSymbolX( 1, "🤡", "Clown Face`n:clown:"                               )
    super.RegisterSymbolX( 1, "👹", "Ogre`n:japanese_ogre:"                             )
    super.RegisterSymbolX( 1, "👺", "Goblin`n:japanese_goblin:"                         )
    super.RegisterSymbolX( 1, "👻", "Ghost`n:ghost:"                                     )

    super.RegisterSymbolX( 1, "👽", "Alien`n:alien:"               )
    super.RegisterSymbolX( 1, "👾", "Alien Monster`n:space_invader:" )
    super.RegisterSymbolX( 1, "🤖", "Robot`n:robot:"               )
    super.RegisterSymbolX( 1, "🎃", "Jack-o-Lantern`n:jack_o_lantern:" )
  }

  ; ─── Smileys & Emotion — Hearts & Love ────────────────────────
  RegisterHeartsAndEmotion()
  {
    super.RegisterSymbolX( 1, "❤️",  "Red Heart`n:heart:"                )
    super.RegisterSymbolX( 1, "🧡",  "Orange Heart`n:orange_heart:"      )
    super.RegisterSymbolX( 1, "💛",  "Yellow Heart`n:yellow_heart:"      )
    super.RegisterSymbolX( 1, "💚",  "Green Heart`n:green_heart:"        )
    super.RegisterSymbolX( 1, "💙",  "Blue Heart`n:blue_heart:"          )
    super.RegisterSymbolX( 1, "💜",  "Purple Heart`n:purple_heart:"      )
    super.RegisterSymbolX( 1, "🖤",  "Black Heart`n:black_heart:"        )
    super.RegisterSymbolX( 1, "🤍",  "White Heart`n:white_heart:"        )
    super.RegisterSymbolX( 1, "🤎",  "Brown Heart`n:brown_heart:"        )
    super.RegisterSymbolX( 1, "💔",  "Broken Heart`n:broken_heart:"      )
    super.RegisterSymbolX( 1, "❣️",  "Heart Exclamation`n:heart_exclamation:" )
    super.RegisterSymbolX( 1, "💕",  "Two Hearts`n:two_hearts:"          )

    super.RegisterSymbolX( 1, "💞",  "Revolving Hearts`n:revolving_hearts:"  )
    super.RegisterSymbolX( 1, "💓",  "Beating Heart`n:heartbeat:"            )
    super.RegisterSymbolX( 1, "💗",  "Growing Heart`n:heartpulse:"           )
    super.RegisterSymbolX( 1, "💖",  "Sparkling Heart`n:sparkling_heart:"    )
    super.RegisterSymbolX( 1, "💘",  "Heart with Arrow`n:cupid:"             )
    super.RegisterSymbolX( 1, "💝",  "Heart with Ribbon`n:gift_heart:"       )
    super.RegisterSymbolX( 1, "💟",  "Heart Decoration`n:heart_decoration:"  )
    super.RegisterSymbolX( 1, "💋",  "Kiss Mark`n:kiss:"                     )
    super.RegisterSymbolX( 1, "💌",  "Love Letter`n:love_letter:"            )
    super.RegisterSymbolX( 1, "💯",  "Hundred Points`n:100:"                 )
    super.RegisterSymbolX( 1, "💢",  "Anger Symbol`n:anger:"                 )
    super.RegisterSymbolX( 1, "💥",  "Collision`n:boom:"                     )

    super.RegisterSymbolX( 1, "💫", "Dizzy`n:dizzy:"          )
    super.RegisterSymbolX( 1, "💦", "Sweat Droplets`n:sweat_drops:" )
    super.RegisterSymbolX( 1, "💨", "Dashing Away`n:dash:"    )
    super.RegisterSymbolX( 1, "💬", "Speech Balloon`n:speech_balloon:" )
    super.RegisterSymbolX( 1, "💭", "Thought Balloon`n:thought_balloon:" )
    super.RegisterSymbolX( 1, "💤", "ZZZ`n:zzz:"              )
    super.RegisterSymbolX( 1, "✨", "Sparkles`n:sparkles:"    )
    super.RegisterSymbolX( 1, "🎵", "Musical Note`n:musical_note:" )
    super.RegisterSymbolX( 1, "🎶", "Musical Notes`n:notes:"   )
    super.RegisterSymbolX( 1, "🔥", "Fire`n:fire:"             )
    super.RegisterSymbolX( 1, "👁️", "Eye`n:eye:"               )
    super.RegisterSymbolX( 1, "💡", "Light Bulb`n:bulb:"      )
  }

  ; ─── People & Body — Gestures ──────────────────────────────────
  RegisterGestures()
  {
    super.RegisterSymbolX( 1, "👋", "Waving Hand`n:wave:"             )
    super.RegisterSymbolX( 1, "🤚", "Raised Back of Hand`n:raised_back_of_hand:" )
    super.RegisterSymbolX( 1, "🖐️", "Hand with Fingers Splayed`n:hand_splayed:" )
    super.RegisterSymbolX( 1, "✋", "Raised Hand`n:raised_hand:"      )
    super.RegisterSymbolX( 1, "🖖", "Vulcan Salute`n:vulcan:"         )
    super.RegisterSymbolX( 1, "👌", "OK Hand`n:ok_hand:"              )
    super.RegisterSymbolX( 1, "🤌", "Pinched Fingers`n:pinched_fingers:" )
    super.RegisterSymbolX( 1, "🤏", "Pinching Hand`n:pinching_hand:"  )
    super.RegisterSymbolX( 1, "✌️", "Victory Hand`n:v:"               )
    super.RegisterSymbolX( 1, "🤞", "Crossed Fingers`n:crossed_fingers:" )
    super.RegisterSymbolX( 1, "🤟", "Love-You Gesture`n:love_you:"    )
    super.RegisterSymbolX( 1, "🤘", "Sign of the Horns`n:metal:"      )

    super.RegisterSymbolX( 1, "🤙", "Call Me Hand`n:call_me_hand:"    )
    super.RegisterSymbolX( 1, "👈", "Backhand Pointing Left`n:point_left:"  )
    super.RegisterSymbolX( 1, "👉", "Backhand Pointing Right`n:point_right:" )
    super.RegisterSymbolX( 1, "👆", "Backhand Pointing Up`n:point_up_2:"    )
    super.RegisterSymbolX( 1, "🖕", "Middle Finger`n:middle_finger:"  )
    super.RegisterSymbolX( 1, "👇", "Backhand Pointing Down`n:point_down:"  )
    super.RegisterSymbolX( 1, "☝️", "Index Pointing Up`n:point_up:"   )
    super.RegisterSymbolX( 1, "👍", "Thumbs Up`n:+1:"                 )
    super.RegisterSymbolX( 1, "👎", "Thumbs Down`n:-1:"               )
    super.RegisterSymbolX( 1, "✊", "Raised Fist`n:fist:"             )
    super.RegisterSymbolX( 1, "👊", "Oncoming Fist`n:facepunch:"      )
    super.RegisterSymbolX( 1, "🤛", "Left-Facing Fist`n:left_fist:"   )

    super.RegisterSymbolX( 1, "🤜", "Right-Facing Fist`n:right_fist:" )
    super.RegisterSymbolX( 1, "👏", "Clapping Hands`n:clap:"          )
    super.RegisterSymbolX( 1, "🙌", "Raising Hands`n:raised_hands:"   )
    super.RegisterSymbolX( 1, "🫶", "Heart Hands`n:heart_hands:"      )
    super.RegisterSymbolX( 1, "👐", "Open Hands`n:open_hands:"        )
    super.RegisterSymbolX( 1, "🤲", "Palms Up Together`n:palms_up:"   )
    super.RegisterSymbolX( 1, "🙏", "Folded Hands`n:pray:"            )
    super.RegisterSymbolX( 1, "✍️", "Writing Hand`n:writing_hand:"    )
    super.RegisterSymbolX( 1, "💅", "Nail Polish`n:nail_care:"        )
    super.RegisterSymbolX( 1, "🤳", "Selfie`n:selfie:"                )
    super.RegisterSymbolX( 1, "💪", "Flexed Biceps`n:muscle:"         )
    super.RegisterSymbolX( 1, "🦾", "Mechanical Arm`n:mechanical_arm:" )
  }

  ; ─── People & Body — People ────────────────────────────────────
  RegisterPeople()
  {
    super.RegisterSymbolX( 1, "👶", "Baby`n:baby:"            )
    super.RegisterSymbolX( 1, "🧒", "Child`n:child:"          )
    super.RegisterSymbolX( 1, "👦", "Boy`n:boy:"              )
    super.RegisterSymbolX( 1, "👧", "Girl`n:girl:"            )
    super.RegisterSymbolX( 1, "🧑", "Person`n:person:"        )
    super.RegisterSymbolX( 1, "👱", "Person Blond Hair`n:blond_haired_person:" )
    super.RegisterSymbolX( 1, "👨", "Man`n:man:"              )
    super.RegisterSymbolX( 1, "🧔", "Person Beard`n:bearded_person:" )
    super.RegisterSymbolX( 1, "👩", "Woman`n:woman:"          )
    super.RegisterSymbolX( 1, "🧓", "Older Person`n:older_person:" )
    super.RegisterSymbolX( 1, "👴", "Old Man`n:older_man:"    )
    super.RegisterSymbolX( 1, "👵", "Old Woman`n:older_woman:" )

    super.RegisterSymbolX( 1, "👮", "Police Officer`n:police_officer:"  )
    super.RegisterSymbolX( 1, "💂", "Guard`n:guard:"                    )
    super.RegisterSymbolX( 1, "🕵️", "Detective`n:detective:"            )
    super.RegisterSymbolX( 1, "👨‍⚕️", "Health Worker`n:health_worker:" )
    super.RegisterSymbolX( 1, "👷", "Construction Worker`n:construction_worker:" )
    super.RegisterSymbolX( 1, "🤴", "Prince`n:prince:"                  )
    super.RegisterSymbolX( 1, "👸", "Princess`n:princess:"              )
    super.RegisterSymbolX( 1, "🎅", "Santa Claus`n:santa:"              )
    super.RegisterSymbolX( 1, "🤶", "Mrs. Claus`n:mrs_claus:"           )
    super.RegisterSymbolX( 1, "🦸", "Superhero`n:superhero:"            )
    super.RegisterSymbolX( 1, "🦹", "Supervillain`n:supervillain:"      )
    super.RegisterSymbolX( 1, "🧙", "Mage`n:mage:"                      )

    super.RegisterSymbolX( 1, "🧝", "Elf`n:elf:"              )
    super.RegisterSymbolX( 1, "🧛", "Vampire`n:vampire:"      )
    super.RegisterSymbolX( 1, "🧟", "Zombie`n:zombie:"        )
    super.RegisterSymbolX( 1, "🧞", "Genie`n:genie:"          )
    super.RegisterSymbolX( 1, "🧜", "Merperson`n:merperson:"  )
    super.RegisterSymbolX( 1, "🧚", "Fairy`n:fairy:"          )
    super.RegisterSymbolX( 1, "👼", "Baby Angel`n:angel:"     )
    super.RegisterSymbolX( 1, "🤰", "Pregnant Woman`n:pregnant_woman:" )
    super.RegisterSymbolX( 1, "🤱", "Breast-Feeding`n:breast_feeding:" )
    super.RegisterSymbolX( 1, "🙍", "Person Frowning`n:person_frowning:" )
    super.RegisterSymbolX( 1, "🙎", "Person Pouting`n:person_pouting:"  )
    super.RegisterSymbolX( 1, "🙅", "Person Gesturing NO`n:no_good:"    )

    super.RegisterSymbolX( 1, "🙆", "Person Gesturing OK`n:ok_woman:"   )
    super.RegisterSymbolX( 1, "💁", "Person Tipping Hand`n:information_desk_person:" )
    super.RegisterSymbolX( 1, "🙋", "Person Raising Hand`n:raising_hand:" )
    super.RegisterSymbolX( 1, "🧏", "Deaf Person`n:deaf_person:"        )
    super.RegisterSymbolX( 1, "🙇", "Person Bowing`n:bow:"              )
    super.RegisterSymbolX( 1, "🤦", "Person Facepalming`n:facepalm:"    )
    super.RegisterSymbolX( 1, "🤷", "Person Shrugging`n:shrug:"         )
    super.RegisterSymbolX( 1, "👫", "Man and Woman Holding Hands`n:couple:" )
    super.RegisterSymbolX( 1, "👬", "Two Men Holding Hands`n:two_men:"  )
    super.RegisterSymbolX( 1, "👭", "Two Women Holding Hands`n:two_women:" )
    super.RegisterSymbolX( 1, "💏", "Kiss`n:couplekiss:"                )
    super.RegisterSymbolX( 1, "💑", "Couple with Heart`n:couple_with_heart:" )
  }

  ; ─── Animals & Nature — Animals ────────────────────────────────
  RegisterAnimals()
  {
    super.RegisterSymbolX( 1, "🐶", "Dog`n:dog:"             )
    super.RegisterSymbolX( 1, "🐱", "Cat`n:cat:"             )
    super.RegisterSymbolX( 1, "🐭", "Mouse`n:mouse:"         )
    super.RegisterSymbolX( 1, "🐹", "Hamster`n:hamster:"     )
    super.RegisterSymbolX( 1, "🐰", "Rabbit`n:rabbit:"       )
    super.RegisterSymbolX( 1, "🦊", "Fox`n:fox_face:"        )
    super.RegisterSymbolX( 1, "🐻", "Bear`n:bear:"           )
    super.RegisterSymbolX( 1, "🐼", "Panda`n:panda_face:"    )
    super.RegisterSymbolX( 1, "🐨", "Koala`n:koala:"         )
    super.RegisterSymbolX( 1, "🐯", "Tiger`n:tiger:"         )
    super.RegisterSymbolX( 1, "🦁", "Lion`n:lion:"           )
    super.RegisterSymbolX( 1, "🐮", "Cow`n:cow:"             )

    super.RegisterSymbolX( 1, "🐷", "Pig`n:pig:"             )
    super.RegisterSymbolX( 1, "🐸", "Frog`n:frog:"           )
    super.RegisterSymbolX( 1, "🐵", "Monkey Face`n:monkey_face:" )
    super.RegisterSymbolX( 1, "🙈", "See-No-Evil Monkey`n:see_no_evil:" )
    super.RegisterSymbolX( 1, "🙉", "Hear-No-Evil Monkey`n:hear_no_evil:" )
    super.RegisterSymbolX( 1, "🙊", "Speak-No-Evil Monkey`n:speak_no_evil:" )
    super.RegisterSymbolX( 1, "🐔", "Chicken`n:chicken:"     )
    super.RegisterSymbolX( 1, "🐧", "Penguin`n:penguin:"     )
    super.RegisterSymbolX( 1, "🐦", "Bird`n:bird:"           )
    super.RegisterSymbolX( 1, "🐤", "Baby Chick`n:baby_chick:" )
    super.RegisterSymbolX( 1, "🦆", "Duck`n:duck:"           )
    super.RegisterSymbolX( 1, "🦅", "Eagle`n:eagle:"         )

    super.RegisterSymbolX( 1, "🦉", "Owl`n:owl:"             )
    super.RegisterSymbolX( 1, "🦇", "Bat`n:bat:"             )
    super.RegisterSymbolX( 1, "🐺", "Wolf`n:wolf:"           )
    super.RegisterSymbolX( 1, "🐗", "Boar`n:boar:"           )
    super.RegisterSymbolX( 1, "🐴", "Horse`n:horse:"         )
    super.RegisterSymbolX( 1, "🦄", "Unicorn`n:unicorn:"     )
    super.RegisterSymbolX( 1, "🐝", "Honeybee`n:bee:"        )
    super.RegisterSymbolX( 1, "🐛", "Bug`n:bug:"             )
    super.RegisterSymbolX( 1, "🦋", "Butterfly`n:butterfly:" )
    super.RegisterSymbolX( 1, "🐌", "Snail`n:snail:"         )
    super.RegisterSymbolX( 1, "🐞", "Lady Beetle`n:beetle:"  )
    super.RegisterSymbolX( 1, "🐜", "Ant`n:ant:"             )

    super.RegisterSymbolX( 1, "🦟", "Mosquito`n:mosquito:"   )
    super.RegisterSymbolX( 1, "🦗", "Cricket`n:cricket:"     )
    super.RegisterSymbolX( 1, "🕷️", "Spider`n:spider:"       )
    super.RegisterSymbolX( 1, "🦂", "Scorpion`n:scorpion:"   )
    super.RegisterSymbolX( 1, "🐢", "Turtle`n:turtle:"       )
    super.RegisterSymbolX( 1, "🐍", "Snake`n:snake:"         )
    super.RegisterSymbolX( 1, "🦎", "Lizard`n:lizard:"       )
    super.RegisterSymbolX( 1, "🐊", "Crocodile`n:crocodile:" )
    super.RegisterSymbolX( 1, "🐙", "Octopus`n:octopus:"     )
    super.RegisterSymbolX( 1, "🦑", "Squid`n:squid:"         )
    super.RegisterSymbolX( 1, "🦐", "Shrimp`n:shrimp:"       )
    super.RegisterSymbolX( 1, "🦞", "Lobster`n:lobster:"     )

    super.RegisterSymbolX( 1, "🦀", "Crab`n:crab:"           )
    super.RegisterSymbolX( 1, "🐡", "Blowfish`n:blowfish:"   )
    super.RegisterSymbolX( 1, "🐠", "Tropical Fish`n:tropical_fish:" )
    super.RegisterSymbolX( 1, "🐟", "Fish`n:fish:"           )
    super.RegisterSymbolX( 1, "🐬", "Dolphin`n:dolphin:"     )
    super.RegisterSymbolX( 1, "🐳", "Spouting Whale`n:whale:" )
    super.RegisterSymbolX( 1, "🐋", "Whale`n:whale2:"        )
    super.RegisterSymbolX( 1, "🦈", "Shark`n:shark:"         )
    super.RegisterSymbolX( 1, "🦓", "Zebra`n:zebra:"         )
    super.RegisterSymbolX( 1, "🦍", "Gorilla`n:gorilla:"     )
    super.RegisterSymbolX( 1, "🦧", "Orangutan`n:orangutan:" )
    super.RegisterSymbolX( 1, "🐘", "Elephant`n:elephant:"   )

    super.RegisterSymbolX( 1, "🦛", "Hippopotamus`n:hippopotamus:" )
    super.RegisterSymbolX( 1, "🦏", "Rhinoceros`n:rhinoceros:"     )
    super.RegisterSymbolX( 1, "🐪", "Camel`n:dromedary_camel:"     )
    super.RegisterSymbolX( 1, "🐫", "Two-Hump Camel`n:camel:"      )
    super.RegisterSymbolX( 1, "🦒", "Giraffe`n:giraffe:"           )
    super.RegisterSymbolX( 1, "🦘", "Kangaroo`n:kangaroo:"         )
    super.RegisterSymbolX( 1, "🐃", "Water Buffalo`n:water_buffalo:" )
    super.RegisterSymbolX( 1, "🐂", "Ox`n:ox:"                     )
    super.RegisterSymbolX( 1, "🐄", "Cow`n:cow2:"                  )
    super.RegisterSymbolX( 1, "🐎", "Horse`n:horse2:"               )
    super.RegisterSymbolX( 1, "🐖", "Pig`n:pig2:"                   )
    super.RegisterSymbolX( 1, "🐏", "Ram`n:ram:"                    )

    super.RegisterSymbolX( 1, "🐑", "Ewe`n:sheep:"           )
    super.RegisterSymbolX( 1, "🦙", "Llama`n:llama:"         )
    super.RegisterSymbolX( 1, "🐐", "Goat`n:goat:"           )
    super.RegisterSymbolX( 1, "🦌", "Deer`n:deer:"           )
    super.RegisterSymbolX( 1, "🐕", "Dog`n:dog2:"            )
    super.RegisterSymbolX( 1, "🐩", "Poodle`n:poodle:"       )
    super.RegisterSymbolX( 1, "🐈", "Cat`n:cat2:"            )
    super.RegisterSymbolX( 1, "🦚", "Peacock`n:peacock:"     )
    super.RegisterSymbolX( 1, "🦜", "Parrot`n:parrot:"       )
    super.RegisterSymbolX( 1, "🦢", "Swan`n:swan:"           )
    super.RegisterSymbolX( 1, "🦩", "Flamingo`n:flamingo:"   )
    super.RegisterSymbolX( 1, "🕊️", "Dove`n:dove:"           )

    super.RegisterSymbolX( 1, "🐇", "Rabbit`n:rabbit2:"      )
    super.RegisterSymbolX( 1, "🦝", "Raccoon`n:raccoon:"     )
    super.RegisterSymbolX( 1, "🦨", "Skunk`n:skunk:"         )
    super.RegisterSymbolX( 1, "🦡", "Badger`n:badger:"       )
    super.RegisterSymbolX( 1, "🦫", "Beaver`n:beaver:"       )
    super.RegisterSymbolX( 1, "🦦", "Otter`n:otter:"         )
    super.RegisterSymbolX( 1, "🦥", "Sloth`n:sloth:"         )
    super.RegisterSymbolX( 1, "🐁", "Mouse`n:mouse2:"        )
    super.RegisterSymbolX( 1, "🐀", "Rat`n:rat:"             )
    super.RegisterSymbolX( 1, "🐿️", "Chipmunk`n:chipmunk:"  )
    super.RegisterSymbolX( 1, "🦔", "Hedgehog`n:hedgehog:"   )
    super.RegisterSymbolX( 1, "🐾", "Paw Prints`n:paw_prints:" )
  }

  ; ─── Animals & Nature — Plants & Sky ───────────────────────────
  RegisterPlantsAndNature()
  {
    super.RegisterSymbolX( 1, "🌵", "Cactus`n:cactus:"          )
    super.RegisterSymbolX( 1, "🎄", "Christmas Tree`n:christmas_tree:" )
    super.RegisterSymbolX( 1, "🌲", "Evergreen Tree`n:evergreen_tree:" )
    super.RegisterSymbolX( 1, "🌳", "Deciduous Tree`n:deciduous_tree:" )
    super.RegisterSymbolX( 1, "🌴", "Palm Tree`n:palm_tree:"    )
    super.RegisterSymbolX( 1, "🌱", "Seedling`n:seedling:"      )
    super.RegisterSymbolX( 1, "🌿", "Herb`n:herb:"              )
    super.RegisterSymbolX( 1, "☘️", "Shamrock`n:shamrock:"      )
    super.RegisterSymbolX( 1, "🍀", "Four Leaf Clover`n:four_leaf_clover:" )
    super.RegisterSymbolX( 1, "🎋", "Tanabata Tree`n:tanabata_tree:" )
    super.RegisterSymbolX( 1, "🎍", "Pine Decoration`n:bamboo:" )
    super.RegisterSymbolX( 1, "🍃", "Leaf Fluttering`n:leaves:" )

    super.RegisterSymbolX( 1, "🍂", "Fallen Leaf`n:fallen_leaf:"  )
    super.RegisterSymbolX( 1, "🍁", "Maple Leaf`n:maple_leaf:"    )
    super.RegisterSymbolX( 1, "🍄", "Mushroom`n:mushroom:"        )
    super.RegisterSymbolX( 1, "🌾", "Sheaf of Rice`n:ear_of_rice:" )
    super.RegisterSymbolX( 1, "💐", "Bouquet`n:bouquet:"          )
    super.RegisterSymbolX( 1, "🌷", "Tulip`n:tulip:"              )
    super.RegisterSymbolX( 1, "🌹", "Rose`n:rose:"                )
    super.RegisterSymbolX( 1, "🥀", "Wilted Flower`n:wilted_flower:" )
    super.RegisterSymbolX( 1, "🌺", "Hibiscus`n:hibiscus:"        )
    super.RegisterSymbolX( 1, "🌸", "Cherry Blossom`n:cherry_blossom:" )
    super.RegisterSymbolX( 1, "🌼", "Blossom`n:blossom:"          )
    super.RegisterSymbolX( 1, "🌻", "Sunflower`n:sunflower:"      )

    super.RegisterSymbolX( 1, "🌞", "Sun with Face`n:sun_with_face:" )
    super.RegisterSymbolX( 1, "🌝", "Full Moon with Face`n:full_moon_face:" )
    super.RegisterSymbolX( 1, "🌛", "First Quarter Moon`n:first_quarter_moon_with_face:" )
    super.RegisterSymbolX( 1, "🌜", "Last Quarter Moon`n:last_quarter_moon_with_face:" )
    super.RegisterSymbolX( 1, "🌚", "New Moon with Face`n:new_moon_with_face:" )
    super.RegisterSymbolX( 1, "🌕", "Full Moon`n:full_moon:"      )
    super.RegisterSymbolX( 1, "🌙", "Crescent Moon`n:crescent_moon:" )
    super.RegisterSymbolX( 1, "🌟", "Glowing Star`n:star2:"       )
    super.RegisterSymbolX( 1, "⭐", "Star`n:star:"                )
    super.RegisterSymbolX( 1, "🌠", "Shooting Star`n:stars:"      )
    super.RegisterSymbolX( 1, "☀️", "Sun`n:sunny:"                )
    super.RegisterSymbolX( 1, "🌈", "Rainbow`n:rainbow:"          )

    super.RegisterSymbolX( 1, "⛅", "Sun Behind Cloud`n:partly_sunny:"  )
    super.RegisterSymbolX( 1, "🌤️", "Sun Behind Small Cloud`n:sun_small_cloud:" )
    super.RegisterSymbolX( 1, "☁️", "Cloud`n:cloud:"                    )
    super.RegisterSymbolX( 1, "🌦️", "Sun Behind Rain Cloud`n:sun_rain:" )
    super.RegisterSymbolX( 1, "🌧️", "Cloud with Rain`n:rain_cloud:"     )
    super.RegisterSymbolX( 1, "⛈️", "Thunder Cloud and Rain`n:thunder_cloud:" )
    super.RegisterSymbolX( 1, "🌩️", "Cloud with Lightning`n:lightning:" )
    super.RegisterSymbolX( 1, "🌨️", "Cloud with Snow`n:snow_cloud:"     )
    super.RegisterSymbolX( 1, "❄️", "Snowflake`n:snowflake:"            )
    super.RegisterSymbolX( 1, "☃️", "Snowman with Snow`n:snowman_with_snow:" )
    super.RegisterSymbolX( 1, "⛄", "Snowman`n:snowman:"                )
    super.RegisterSymbolX( 1, "🌬️", "Wind Face`n:wind_blowing_face:"    )

    super.RegisterSymbolX( 1, "🌊", "Water Wave`n:ocean:"      )
    super.RegisterSymbolX( 1, "🌀", "Cyclone`n:cyclone:"       )
    super.RegisterSymbolX( 1, "🌪️", "Tornado`n:tornado:"       )
    super.RegisterSymbolX( 1, "🌫️", "Fog`n:fog:"               )
    super.RegisterSymbolX( 1, "🌈", "Rainbow`n:rainbow2:"      )
    super.RegisterSymbolX( 1, "☔", "Umbrella with Rain`n:umbrella:" )
    super.RegisterSymbolX( 1, "⚡", "Lightning`n:zap:"          )
    super.RegisterSymbolX( 1, "🌋", "Volcano`n:volcano:"        )
    super.RegisterSymbolX( 1, "🏔️", "Snow-Capped Mountain`n:snow_capped_mountain:" )
    super.RegisterSymbolX( 1, "⛰️", "Mountain`n:mountain:"     )
    super.RegisterSymbolX( 1, "🏕️", "Camping`n:camping:"       )
    super.RegisterSymbolX( 1, "🌌", "Milky Way`n:milky_way:"   )
  }

  ; ─── Food & Drink ──────────────────────────────────────────────
  RegisterFoodAndDrink()
  {
    super.RegisterSymbolX( 1, "🍎", "Red Apple`n:apple:"          )
    super.RegisterSymbolX( 1, "🍐", "Pear`n:pear:"                )
    super.RegisterSymbolX( 1, "🍊", "Tangerine`n:tangerine:"      )
    super.RegisterSymbolX( 1, "🍋", "Lemon`n:lemon:"              )
    super.RegisterSymbolX( 1, "🍌", "Banana`n:banana:"            )
    super.RegisterSymbolX( 1, "🍉", "Watermelon`n:watermelon:"    )
    super.RegisterSymbolX( 1, "🍇", "Grapes`n:grapes:"            )
    super.RegisterSymbolX( 1, "🍓", "Strawberry`n:strawberry:"    )
    super.RegisterSymbolX( 1, "🫐", "Blueberries`n:blueberries:"  )
    super.RegisterSymbolX( 1, "🍈", "Melon`n:melon:"              )
    super.RegisterSymbolX( 1, "🍒", "Cherries`n:cherries:"        )
    super.RegisterSymbolX( 1, "🍑", "Peach`n:peach:"              )

    super.RegisterSymbolX( 1, "🥭", "Mango`n:mango:"              )
    super.RegisterSymbolX( 1, "🍍", "Pineapple`n:pineapple:"      )
    super.RegisterSymbolX( 1, "🥥", "Coconut`n:coconut:"          )
    super.RegisterSymbolX( 1, "🥝", "Kiwi`n:kiwi:"                )
    super.RegisterSymbolX( 1, "🍅", "Tomato`n:tomato:"            )
    super.RegisterSymbolX( 1, "🍆", "Eggplant`n:eggplant:"        )
    super.RegisterSymbolX( 1, "🥑", "Avocado`n:avocado:"          )
    super.RegisterSymbolX( 1, "🥦", "Broccoli`n:broccoli:"        )
    super.RegisterSymbolX( 1, "🥬", "Leafy Green`n:leafy_green:"  )
    super.RegisterSymbolX( 1, "🥒", "Cucumber`n:cucumber:"        )
    super.RegisterSymbolX( 1, "🌶️", "Hot Pepper`n:hot_pepper:"    )
    super.RegisterSymbolX( 1, "🧄", "Garlic`n:garlic:"            )

    super.RegisterSymbolX( 1, "🧅", "Onion`n:onion:"              )
    super.RegisterSymbolX( 1, "🥔", "Potato`n:potato:"            )
    super.RegisterSymbolX( 1, "🥕", "Carrot`n:carrot:"            )
    super.RegisterSymbolX( 1, "🌽", "Ear of Corn`n:corn:"         )
    super.RegisterSymbolX( 1, "🥜", "Peanuts`n:peanuts:"          )
    super.RegisterSymbolX( 1, "🍞", "Bread`n:bread:"              )
    super.RegisterSymbolX( 1, "🥐", "Croissant`n:croissant:"      )
    super.RegisterSymbolX( 1, "🧀", "Cheese Wedge`n:cheese:"      )
    super.RegisterSymbolX( 1, "🥚", "Egg`n:egg:"                  )
    super.RegisterSymbolX( 1, "🍳", "Cooking`n:fried_egg:"        )
    super.RegisterSymbolX( 1, "🥞", "Pancakes`n:pancakes:"        )
    super.RegisterSymbolX( 1, "🧇", "Waffle`n:waffle:"            )

    super.RegisterSymbolX( 1, "🥓", "Bacon`n:bacon:"              )
    super.RegisterSymbolX( 1, "🥩", "Cut of Meat`n:cut_of_meat:"  )
    super.RegisterSymbolX( 1, "🍗", "Poultry Leg`n:poultry_leg:"  )
    super.RegisterSymbolX( 1, "🍖", "Meat on Bone`n:meat_on_bone:" )
    super.RegisterSymbolX( 1, "🌭", "Hot Dog`n:hotdog:"           )
    super.RegisterSymbolX( 1, "🍔", "Hamburger`n:hamburger:"      )
    super.RegisterSymbolX( 1, "🍟", "French Fries`n:fries:"       )
    super.RegisterSymbolX( 1, "🍕", "Pizza`n:pizza:"              )
    super.RegisterSymbolX( 1, "🌮", "Taco`n:taco:"                )
    super.RegisterSymbolX( 1, "🌯", "Burrito`n:burrito:"          )
    super.RegisterSymbolX( 1, "🥙", "Stuffed Flatbread`n:stuffed_flatbread:" )
    super.RegisterSymbolX( 1, "🥗", "Green Salad`n:green_salad:"  )

    super.RegisterSymbolX( 1, "🍝", "Spaghetti`n:spaghetti:"      )
    super.RegisterSymbolX( 1, "🍜", "Steaming Bowl`n:ramen:"      )
    super.RegisterSymbolX( 1, "🍲", "Pot of Food`n:stew:"         )
    super.RegisterSymbolX( 1, "🍛", "Curry Rice`n:curry:"         )
    super.RegisterSymbolX( 1, "🍣", "Sushi`n:sushi:"              )
    super.RegisterSymbolX( 1, "🍱", "Bento Box`n:bento:"          )
    super.RegisterSymbolX( 1, "🥟", "Dumpling`n:dumpling:"        )
    super.RegisterSymbolX( 1, "🍤", "Fried Shrimp`n:fried_shrimp:" )
    super.RegisterSymbolX( 1, "🍙", "Rice Ball`n:rice_ball:"      )
    super.RegisterSymbolX( 1, "🍚", "Cooked Rice`n:rice:"         )
    super.RegisterSymbolX( 1, "🍦", "Soft Ice Cream`n:icecream:"  )
    super.RegisterSymbolX( 1, "🍧", "Shaved Ice`n:shaved_ice:"    )

    super.RegisterSymbolX( 1, "🍨", "Ice Cream`n:ice_cream:"      )
    super.RegisterSymbolX( 1, "🧁", "Cupcake`n:cupcake:"          )
    super.RegisterSymbolX( 1, "🎂", "Birthday Cake`n:birthday:"   )
    super.RegisterSymbolX( 1, "🍰", "Shortcake`n:cake:"           )
    super.RegisterSymbolX( 1, "🍮", "Custard`n:custard:"          )
    super.RegisterSymbolX( 1, "🍭", "Lollipop`n:lollipop:"        )
    super.RegisterSymbolX( 1, "🍬", "Candy`n:candy:"              )
    super.RegisterSymbolX( 1, "🍫", "Chocolate Bar`n:chocolate_bar:" )
    super.RegisterSymbolX( 1, "🍿", "Popcorn`n:popcorn:"          )
    super.RegisterSymbolX( 1, "🍩", "Doughnut`n:doughnut:"        )
    super.RegisterSymbolX( 1, "🍪", "Cookie`n:cookie:"            )
    super.RegisterSymbolX( 1, "🌰", "Chestnut`n:chestnut:"        )

    super.RegisterSymbolX( 1, "☕", "Hot Beverage`n:coffee:"     )
    super.RegisterSymbolX( 1, "🍵", "Teacup`n:tea:"              )
    super.RegisterSymbolX( 1, "🧃", "Beverage Box`n:beverage_box:" )
    super.RegisterSymbolX( 1, "🥤", "Cup with Straw`n:cup_with_straw:" )
    super.RegisterSymbolX( 1, "🧋", "Bubble Tea`n:bubble_tea:"   )
    super.RegisterSymbolX( 1, "🍺", "Beer Mug`n:beer:"           )
    super.RegisterSymbolX( 1, "🍻", "Clinking Beer Mugs`n:beers:" )
    super.RegisterSymbolX( 1, "🥂", "Clinking Glasses`n:clinking_glasses:" )
    super.RegisterSymbolX( 1, "🍷", "Wine Glass`n:wine_glass:"   )
    super.RegisterSymbolX( 1, "🥃", "Tumbler Glass`n:tumbler_glass:" )
    super.RegisterSymbolX( 1, "🍸", "Cocktail Glass`n:cocktail:" )
    super.RegisterSymbolX( 1, "🍹", "Tropical Drink`n:tropical_drink:" )
  }

  ; ─── Travel & Places ───────────────────────────────────────────
  RegisterTravelAndPlaces()
  {
    super.RegisterSymbolX( 1, "🚗", "Automobile`n:car:"           )
    super.RegisterSymbolX( 1, "🚕", "Taxi`n:taxi:"                )
    super.RegisterSymbolX( 1, "🚙", "Sport Utility Vehicle`n:blue_car:" )
    super.RegisterSymbolX( 1, "🚌", "Bus`n:bus:"                  )
    super.RegisterSymbolX( 1, "🚎", "Trolleybus`n:trolleybus:"    )
    super.RegisterSymbolX( 1, "🏎️", "Racing Car`n:racing_car:"    )
    super.RegisterSymbolX( 1, "🚓", "Police Car`n:police_car:"    )
    super.RegisterSymbolX( 1, "🚑", "Ambulance`n:ambulance:"      )
    super.RegisterSymbolX( 1, "🚒", "Fire Engine`n:fire_engine:"  )
    super.RegisterSymbolX( 1, "🚐", "Minibus`n:minibus:"          )
    super.RegisterSymbolX( 1, "🚚", "Delivery Truck`n:truck:"     )
    super.RegisterSymbolX( 1, "🚛", "Articulated Lorry`n:articulated_lorry:" )

    super.RegisterSymbolX( 1, "🚜", "Tractor`n:tractor:"          )
    super.RegisterSymbolX( 1, "🏍️", "Motorcycle`n:motorcycle:"    )
    super.RegisterSymbolX( 1, "🛵", "Motor Scooter`n:motor_scooter:" )
    super.RegisterSymbolX( 1, "🚲", "Bicycle`n:bike:"             )
    super.RegisterSymbolX( 1, "🛴", "Kick Scooter`n:scooter:"     )
    super.RegisterSymbolX( 1, "🚁", "Helicopter`n:helicopter:"    )
    super.RegisterSymbolX( 1, "🛸", "Flying Saucer`n:flying_saucer:" )
    super.RegisterSymbolX( 1, "✈️", "Airplane`n:airplane:"        )
    super.RegisterSymbolX( 1, "🚀", "Rocket`n:rocket:"            )
    super.RegisterSymbolX( 1, "🛩️", "Small Airplane`n:small_airplane:" )
    super.RegisterSymbolX( 1, "⛵", "Sailboat`n:sailboat:"        )
    super.RegisterSymbolX( 1, "🚤", "Speedboat`n:speedboat:"      )

    super.RegisterSymbolX( 1, "🛳️", "Passenger Ship`n:passenger_ship:" )
    super.RegisterSymbolX( 1, "🚢", "Ship`n:ship:"                )
    super.RegisterSymbolX( 1, "🚂", "Locomotive`n:steam_locomotive:" )
    super.RegisterSymbolX( 1, "🚄", "High-Speed Train`n:bullettrain_side:" )
    super.RegisterSymbolX( 1, "🚇", "Metro`n:metro:"              )
    super.RegisterSymbolX( 1, "🚊", "Tram`n:tram:"                )
    super.RegisterSymbolX( 1, "🚞", "Mountain Railway`n:mountain_railway:" )
    super.RegisterSymbolX( 1, "⛽", "Fuel Pump`n:fuelpump:"       )
    super.RegisterSymbolX( 1, "🚦", "Vertical Traffic Light`n:vertical_traffic_light:" )
    super.RegisterSymbolX( 1, "🚥", "Horizontal Traffic Light`n:traffic_light:" )
    super.RegisterSymbolX( 1, "🚧", "Construction`n:construction:" )
    super.RegisterSymbolX( 1, "🗺️", "World Map`n:world_map:"      )

    super.RegisterSymbolX( 1, "🧭", "Compass`n:compass:"          )
    super.RegisterSymbolX( 1, "🏠", "House`n:house:"              )
    super.RegisterSymbolX( 1, "🏡", "House with Garden`n:house_with_garden:" )
    super.RegisterSymbolX( 1, "🏢", "Office Building`n:office:"   )
    super.RegisterSymbolX( 1, "🏥", "Hospital`n:hospital:"        )
    super.RegisterSymbolX( 1, "🏦", "Bank`n:bank:"                )
    super.RegisterSymbolX( 1, "🏨", "Hotel`n:hotel:"              )
    super.RegisterSymbolX( 1, "🏪", "Convenience Store`n:convenience_store:" )
    super.RegisterSymbolX( 1, "🏫", "School`n:school:"            )
    super.RegisterSymbolX( 1, "🏰", "Castle`n:european_castle:"   )
    super.RegisterSymbolX( 1, "🏯", "Japanese Castle`n:japanese_castle:" )
    super.RegisterSymbolX( 1, "🗼", "Tokyo Tower`n:tokyo_tower:"  )

    super.RegisterSymbolX( 1, "🗽", "Statue of Liberty`n:statue_of_liberty:" )
    super.RegisterSymbolX( 1, "⛪", "Church`n:church:"            )
    super.RegisterSymbolX( 1, "🕌", "Mosque`n:mosque:"            )
    super.RegisterSymbolX( 1, "🕍", "Synagogue`n:synagogue:"      )
    super.RegisterSymbolX( 1, "⛩️", "Shinto Shrine`n:shinto_shrine:" )
    super.RegisterSymbolX( 1, "🕋", "Kaaba`n:kaaba:"              )
    super.RegisterSymbolX( 1, "⛲", "Fountain`n:fountain:"        )
    super.RegisterSymbolX( 1, "🏟️", "Stadium`n:stadium:"          )
    super.RegisterSymbolX( 1, "🌁", "Foggy`n:foggy:"              )
    super.RegisterSymbolX( 1, "🌃", "Night with Stars`n:night_with_stars:" )
    super.RegisterSymbolX( 1, "🏙️", "Cityscape`n:cityscape:"      )
    super.RegisterSymbolX( 1, "🌄", "Sunrise over Mountains`n:sunrise_over_mountains:" )

    super.RegisterSymbolX( 1, "🌅", "Sunrise`n:sunrise:"          )
    super.RegisterSymbolX( 1, "🌆", "Cityscape at Dusk`n:city_sunrise:" )
    super.RegisterSymbolX( 1, "🌇", "Sunset`n:city_sunset:"       )
    super.RegisterSymbolX( 1, "🌉", "Bridge at Night`n:bridge_at_night:" )
    super.RegisterSymbolX( 1, "🏔️", "Snow-Capped Mountain`n:mountain_snow:" )
    super.RegisterSymbolX( 1, "🏜️", "Desert`n:desert:"            )
    super.RegisterSymbolX( 1, "🏝️", "Desert Island`n:desert_island:" )
    super.RegisterSymbolX( 1, "🏞️", "National Park`n:national_park:" )
    super.RegisterSymbolX( 1, "🗻", "Mount Fuji`n:mount_fuji:"    )
    super.RegisterSymbolX( 1, "🌐", "Globe with Meridians`n:globe_with_meridians:" )
    super.RegisterSymbolX( 1, "🌍", "Globe Europe-Africa`n:earth_africa:" )
    super.RegisterSymbolX( 1, "🌎", "Globe Americas`n:earth_americas:" )
  }

  ; ─── Activities ────────────────────────────────────────────────
  RegisterActivities()
  {
    super.RegisterSymbolX( 1, "⚽", "Soccer Ball`n:soccer:"       )
    super.RegisterSymbolX( 1, "🏀", "Basketball`n:basketball:"    )
    super.RegisterSymbolX( 1, "🏈", "American Football`n:football:" )
    super.RegisterSymbolX( 1, "⚾", "Baseball`n:baseball:"        )
    super.RegisterSymbolX( 1, "🥎", "Softball`n:softball:"        )
    super.RegisterSymbolX( 1, "🎾", "Tennis`n:tennis:"            )
    super.RegisterSymbolX( 1, "🏐", "Volleyball`n:volleyball:"    )
    super.RegisterSymbolX( 1, "🏉", "Rugby Football`n:rugby_football:" )
    super.RegisterSymbolX( 1, "🥏", "Flying Disc`n:flying_disc:"  )
    super.RegisterSymbolX( 1, "🎱", "Pool 8 Ball`n:8ball:"        )
    super.RegisterSymbolX( 1, "🏓", "Ping Pong`n:ping_pong:"      )
    super.RegisterSymbolX( 1, "🏸", "Badminton`n:badminton:"      )

    super.RegisterSymbolX( 1, "🥍", "Lacrosse`n:lacrosse:"        )
    super.RegisterSymbolX( 1, "🏒", "Ice Hockey`n:ice_hockey:"    )
    super.RegisterSymbolX( 1, "🏑", "Field Hockey`n:field_hockey:" )
    super.RegisterSymbolX( 1, "🏏", "Cricket Game`n:cricket_game:" )
    super.RegisterSymbolX( 1, "⛳", "Flag in Hole`n:golf:"         )
    super.RegisterSymbolX( 1, "🎣", "Fishing Pole`n:fishing_pole_and_fish:" )
    super.RegisterSymbolX( 1, "🤿", "Diving Mask`n:diving_mask:"  )
    super.RegisterSymbolX( 1, "🥊", "Boxing Glove`n:boxing_glove:" )
    super.RegisterSymbolX( 1, "🥋", "Martial Arts Uniform`n:martial_arts_uniform:" )
    super.RegisterSymbolX( 1, "🎯", "Direct Hit`n:dart:"          )
    super.RegisterSymbolX( 1, "🪃", "Boomerang`n:boomerang:"      )
    super.RegisterSymbolX( 1, "🏹", "Bow and Arrow`n:bow_and_arrow:" )

    super.RegisterSymbolX( 1, "🎿", "Skis`n:ski:"                 )
    super.RegisterSymbolX( 1, "🛷", "Sled`n:sled:"                )
    super.RegisterSymbolX( 1, "🥌", "Curling Stone`n:curling_stone:" )
    super.RegisterSymbolX( 1, "🛹", "Skateboard`n:skateboard:"    )
    super.RegisterSymbolX( 1, "🪂", "Parachute`n:parachute:"      )
    super.RegisterSymbolX( 1, "🏋️", "Weightlifter`n:weight_lifter:" )
    super.RegisterSymbolX( 1, "🤼", "Wrestlers`n:wrestlers:"      )
    super.RegisterSymbolX( 1, "🤸", "Gymnast`n:person_doing_cartwheel:" )
    super.RegisterSymbolX( 1, "⛷️", "Skier`n:skier:"              )
    super.RegisterSymbolX( 1, "🏂", "Snowboarder`n:snowboarder:"   )
    super.RegisterSymbolX( 1, "🏊", "Swimmer`n:swimmer:"          )
    super.RegisterSymbolX( 1, "🚵", "Mountain Biker`n:mountain_bicyclist:" )

    super.RegisterSymbolX( 1, "🚴", "Bicyclist`n:bicyclist:"      )
    super.RegisterSymbolX( 1, "🧘", "Person Meditating`n:person_in_lotus_position:" )
    super.RegisterSymbolX( 1, "🎮", "Video Game`n:video_game:"    )
    super.RegisterSymbolX( 1, "🕹️", "Joystick`n:joystick:"        )
    super.RegisterSymbolX( 1, "🎰", "Slot Machine`n:slot_machine:" )
    super.RegisterSymbolX( 1, "🧩", "Puzzle Piece`n:jigsaw:"      )
    super.RegisterSymbolX( 1, "🎲", "Game Die`n:game_die:"        )
    super.RegisterSymbolX( 1, "♟️", "Chess Pawn`n:chess_pawn:"    )
    super.RegisterSymbolX( 1, "🎭", "Performing Arts`n:performing_arts:" )
    super.RegisterSymbolX( 1, "🎨", "Artist Palette`n:art:"       )
    super.RegisterSymbolX( 1, "🖌️", "Paintbrush`n:paintbrush:"    )
    super.RegisterSymbolX( 1, "🎬", "Clapper Board`n:clapper:"    )

    super.RegisterSymbolX( 1, "🎤", "Microphone`n:microphone:"    )
    super.RegisterSymbolX( 1, "🎧", "Headphones`n:headphones:"    )
    super.RegisterSymbolX( 1, "🎼", "Musical Score`n:musical_score:" )
    super.RegisterSymbolX( 1, "🎷", "Saxophone`n:saxophone:"      )
    super.RegisterSymbolX( 1, "🎸", "Guitar`n:guitar:"            )
    super.RegisterSymbolX( 1, "🎹", "Musical Keyboard`n:musical_keyboard:" )
    super.RegisterSymbolX( 1, "🎺", "Trumpet`n:trumpet:"          )
    super.RegisterSymbolX( 1, "🎻", "Violin`n:violin:"            )
    super.RegisterSymbolX( 1, "🥁", "Drum`n:drum_with_drumsticks:" )
    super.RegisterSymbolX( 1, "🪘", "Long Drum`n:long_drum:"      )
    super.RegisterSymbolX( 1, "🪗", "Accordion`n:accordion:"      )
    super.RegisterSymbolX( 1, "🎪", "Circus Tent`n:circus_tent:"  )

    super.RegisterSymbolX( 1, "🎠", "Carousel Horse`n:carousel_horse:" )
    super.RegisterSymbolX( 1, "🎡", "Ferris Wheel`n:ferris_wheel:" )
    super.RegisterSymbolX( 1, "🎢", "Roller Coaster`n:roller_coaster:" )
    super.RegisterSymbolX( 1, "🎟️", "Admission Ticket`n:tickets:"  )
    super.RegisterSymbolX( 1, "🎈", "Balloon`n:balloon:"          )
    super.RegisterSymbolX( 1, "🎉", "Party Popper`n:tada:"        )
    super.RegisterSymbolX( 1, "🎊", "Confetti Ball`n:confetti_ball:" )
    super.RegisterSymbolX( 1, "🎁", "Wrapped Gift`n:gift:"        )
    super.RegisterSymbolX( 1, "🎀", "Ribbon`n:ribbon:"            )
    super.RegisterSymbolX( 1, "🎗️", "Reminder Ribbon`n:reminder_ribbon:" )
    super.RegisterSymbolX( 1, "🏆", "Trophy`n:trophy:"            )
    super.RegisterSymbolX( 1, "🥇", "1st Place Medal`n:1st_place_medal:" )

    super.RegisterSymbolX( 1, "🥈", "2nd Place Medal`n:2nd_place_medal:" )
    super.RegisterSymbolX( 1, "🥉", "3rd Place Medal`n:3rd_place_medal:" )
    super.RegisterSymbolX( 1, "🏅", "Sports Medal`n:medal_sports:" )
  }

  ; ─── Objects ───────────────────────────────────────────────────
  RegisterObjects()
  {
    super.RegisterSymbolX( 1, "💻", "Laptop`n:computer:"           )
    super.RegisterSymbolX( 1, "🖥️", "Desktop Computer`n:desktop_computer:" )
    super.RegisterSymbolX( 1, "🖨️", "Printer`n:printer:"           )
    super.RegisterSymbolX( 1, "⌨️", "Keyboard`n:keyboard:"         )
    super.RegisterSymbolX( 1, "🖱️", "Computer Mouse`n:three_button_mouse:" )
    super.RegisterSymbolX( 1, "💾", "Floppy Disk`n:floppy_disk:"   )
    super.RegisterSymbolX( 1, "💿", "Optical Disk`n:cd:"           )
    super.RegisterSymbolX( 1, "📀", "DVD`n:dvd:"                   )
    super.RegisterSymbolX( 1, "📱", "Mobile Phone`n:iphone:"       )
    super.RegisterSymbolX( 1, "📞", "Telephone Receiver`n:telephone_receiver:" )
    super.RegisterSymbolX( 1, "☎️", "Telephone`n:telephone:"       )
    super.RegisterSymbolX( 1, "📺", "Television`n:tv:"             )

    super.RegisterSymbolX( 1, "📷", "Camera`n:camera:"             )
    super.RegisterSymbolX( 1, "📸", "Camera with Flash`n:camera_flash:" )
    super.RegisterSymbolX( 1, "📹", "Video Camera`n:video_camera:" )
    super.RegisterSymbolX( 1, "🎥", "Movie Camera`n:movie_camera:" )
    super.RegisterSymbolX( 1, "📡", "Satellite Antenna`n:satellite:" )
    super.RegisterSymbolX( 1, "🔭", "Telescope`n:telescope:"       )
    super.RegisterSymbolX( 1, "🔬", "Microscope`n:microscope:"     )
    super.RegisterSymbolX( 1, "💡", "Light Bulb`n:bulb2:"          )
    super.RegisterSymbolX( 1, "🔦", "Flashlight`n:flashlight:"     )
    super.RegisterSymbolX( 1, "🕯️", "Candle`n:candle:"             )
    super.RegisterSymbolX( 1, "🔋", "Battery`n:battery:"           )
    super.RegisterSymbolX( 1, "🔌", "Electric Plug`n:electric_plug:" )

    super.RegisterSymbolX( 1, "🧲", "Magnet`n:magnet:"             )
    super.RegisterSymbolX( 1, "⚗️", "Alembic`n:alembic:"           )
    super.RegisterSymbolX( 1, "🧬", "DNA`n:dna:"                   )
    super.RegisterSymbolX( 1, "🩺", "Stethoscope`n:stethoscope:"   )
    super.RegisterSymbolX( 1, "💊", "Pill`n:pill:"                 )
    super.RegisterSymbolX( 1, "🩹", "Adhesive Bandage`n:adhesive_bandage:" )
    super.RegisterSymbolX( 1, "💉", "Syringe`n:syringe:"           )
    super.RegisterSymbolX( 1, "🧪", "Test Tube`n:test_tube:"       )
    super.RegisterSymbolX( 1, "🔨", "Hammer`n:hammer:"             )
    super.RegisterSymbolX( 1, "🪓", "Axe`n:axe:"                   )
    super.RegisterSymbolX( 1, "⚒️", "Hammer and Pick`n:hammer_and_pick:" )
    super.RegisterSymbolX( 1, "🛠️", "Hammer and Wrench`n:hammer_and_wrench:" )

    super.RegisterSymbolX( 1, "🔧", "Wrench`n:wrench:"             )
    super.RegisterSymbolX( 1, "🔩", "Nut and Bolt`n:nut_and_bolt:" )
    super.RegisterSymbolX( 1, "⚙️", "Gear`n:gear:"                 )
    super.RegisterSymbolX( 1, "🔑", "Key`n:key:"                   )
    super.RegisterSymbolX( 1, "🗝️", "Old Key`n:old_key:"           )
    super.RegisterSymbolX( 1, "🔒", "Locked`n:lock:"               )
    super.RegisterSymbolX( 1, "🔓", "Unlocked`n:unlock:"           )
    super.RegisterSymbolX( 1, "✂️", "Scissors`n:scissors:"         )
    super.RegisterSymbolX( 1, "📦", "Package`n:package:"           )
    super.RegisterSymbolX( 1, "📫", "Closed Mailbox`n:mailbox:"    )
    super.RegisterSymbolX( 1, "📝", "Memo`n:memo:"                 )
    super.RegisterSymbolX( 1, "📋", "Clipboard`n:clipboard:"       )

    super.RegisterSymbolX( 1, "📊", "Bar Chart`n:bar_chart:"       )
    super.RegisterSymbolX( 1, "📈", "Chart Increasing`n:chart_with_upwards_trend:" )
    super.RegisterSymbolX( 1, "📉", "Chart Decreasing`n:chart_with_downwards_trend:" )
    super.RegisterSymbolX( 1, "📅", "Calendar`n:calendar:"         )
    super.RegisterSymbolX( 1, "📌", "Pushpin`n:pushpin:"           )
    super.RegisterSymbolX( 1, "📍", "Round Pushpin`n:round_pushpin:" )
    super.RegisterSymbolX( 1, "📎", "Paperclip`n:paperclip:"       )
    super.RegisterSymbolX( 1, "📏", "Straight Ruler`n:straight_ruler:" )
    super.RegisterSymbolX( 1, "📐", "Triangular Ruler`n:triangular_ruler:" )
    super.RegisterSymbolX( 1, "🖊️", "Pen`n:pen_ballpoint:"        )
    super.RegisterSymbolX( 1, "✒️", "Black Nib`n:black_nib:"      )
    super.RegisterSymbolX( 1, "🔍", "Magnifying Glass Left`n:mag:" )

    super.RegisterSymbolX( 1, "📚", "Books`n:books:"               )
    super.RegisterSymbolX( 1, "📖", "Open Book`n:open_book:"       )
    super.RegisterSymbolX( 1, "📰", "Newspaper`n:newspaper:"       )
    super.RegisterSymbolX( 1, "🗂️", "Card Index Dividers`n:card_index_dividers:" )
    super.RegisterSymbolX( 1, "🗑️", "Wastebasket`n:wastebasket:"   )
    super.RegisterSymbolX( 1, "🔐", "Locked with Key`n:closed_lock_with_key:" )
    super.RegisterSymbolX( 1, "🪬", "Hamsa`n:hamsa:"               )
    super.RegisterSymbolX( 1, "🧿", "Nazar Amulet`n:nazar_amulet:" )
    super.RegisterSymbolX( 1, "🏮", "Red Paper Lantern`n:izakaya_lantern:" )
    super.RegisterSymbolX( 1, "💈", "Barber Pole`n:barber:"        )
    super.RegisterSymbolX( 1, "🪞", "Mirror`n:mirror:"             )
    super.RegisterSymbolX( 1, "🪑", "Chair`n:chair:"               )
  }

  ; ─── Symbols ───────────────────────────────────────────────────
  RegisterSymbols()
  {
    super.RegisterSymbolX( 1, "⛔", "No Entry`n:no_entry:"         )
    super.RegisterSymbolX( 1, "🚫", "Prohibited`n:no_entry_sign:"  )
    super.RegisterSymbolX( 1, "🚳", "No Bicycles`n:no_bicycles:"   )
    super.RegisterSymbolX( 1, "🚭", "No Smoking`n:no_smoking:"     )
    super.RegisterSymbolX( 1, "🚯", "No Littering`n:do_not_litter:" )
    super.RegisterSymbolX( 1, "🚱", "Non-Potable Water`n:non_potable_water:" )
    super.RegisterSymbolX( 1, "🚷", "No Pedestrians`n:no_pedestrians:" )
    super.RegisterSymbolX( 1, "📵", "No Mobile Phones`n:no_mobile_phones:" )
    super.RegisterSymbolX( 1, "🔞", "No One Under 18`n:underage:"  )
    super.RegisterSymbolX( 1, "✅", "Check Mark Button`n:white_check_mark:" )
    super.RegisterSymbolX( 1, "❌", "Cross Mark`n:x:"              )
    super.RegisterSymbolX( 1, "❎", "Cross Mark Button`n:negative_squared_cross_mark:" )

    super.RegisterSymbolX( 1, "‼️", "Double Exclamation`n:bangbang:"  )
    super.RegisterSymbolX( 1, "⁉️", "Exclamation Question`n:interrobang:" )
    super.RegisterSymbolX( 1, "❓", "Question Mark`n:question:"     )
    super.RegisterSymbolX( 1, "❔", "White Question Mark`n:grey_question:" )
    super.RegisterSymbolX( 1, "❕", "White Exclamation Mark`n:grey_exclamation:" )
    super.RegisterSymbolX( 1, "❗", "Exclamation Mark`n:exclamation:" )
    super.RegisterSymbolX( 1, "🔔", "Bell`n:bell:"                 )
    super.RegisterSymbolX( 1, "🔕", "Bell with Slash`n:no_bell:"   )
    super.RegisterSymbolX( 1, "🔇", "Muted Speaker`n:mute:"        )
    super.RegisterSymbolX( 1, "🔈", "Speaker Low Volume`n:sound:"  )
    super.RegisterSymbolX( 1, "🔉", "Speaker Medium Volume`n:loudspeaker:" )
    super.RegisterSymbolX( 1, "🔊", "Speaker High Volume`n:loud_sound:" )

    super.RegisterSymbolX( 1, "🔴", "Red Circle`n:red_circle:"     )
    super.RegisterSymbolX( 1, "🟠", "Orange Circle`n:orange_circle:" )
    super.RegisterSymbolX( 1, "🟡", "Yellow Circle`n:yellow_circle:" )
    super.RegisterSymbolX( 1, "🟢", "Green Circle`n:green_circle:" )
    super.RegisterSymbolX( 1, "🔵", "Blue Circle`n:blue_circle:"   )
    super.RegisterSymbolX( 1, "🟣", "Purple Circle`n:purple_circle:" )
    super.RegisterSymbolX( 1, "⚫", "Black Circle`n:black_circle:" )
    super.RegisterSymbolX( 1, "⚪", "White Circle`n:white_circle:" )
    super.RegisterSymbolX( 1, "🟤", "Brown Circle`n:brown_circle:" )
    super.RegisterSymbolX( 1, "🔶", "Large Orange Diamond`n:large_orange_diamond:" )
    super.RegisterSymbolX( 1, "🔷", "Large Blue Diamond`n:large_blue_diamond:" )
    super.RegisterSymbolX( 1, "🔸", "Small Orange Diamond`n:small_orange_diamond:" )

    super.RegisterSymbolX( 1, "🔹", "Small Blue Diamond`n:small_blue_diamond:" )
    super.RegisterSymbolX( 1, "🔺", "Red Triangle Up`n:small_red_triangle:" )
    super.RegisterSymbolX( 1, "🔻", "Red Triangle Down`n:small_red_triangle_down:" )
    super.RegisterSymbolX( 1, "💠", "Diamond with Dot`n:diamond_shape_with_a_dot_inside:" )
    super.RegisterSymbolX( 1, "🔘", "Radio Button`n:radio_button:" )
    super.RegisterSymbolX( 1, "🔲", "Black Square Button`n:black_square_button:" )
    super.RegisterSymbolX( 1, "🔳", "White Square Button`n:white_square_button:" )
    super.RegisterSymbolX( 1, "♻️", "Recycling Symbol`n:recycle:"  )
    super.RegisterSymbolX( 1, "⚜️", "Fleur-de-Lis`n:fleur_de_lis:" )
    super.RegisterSymbolX( 1, "🔱", "Trident Emblem`n:trident:"    )
    super.RegisterSymbolX( 1, "📛", "Name Badge`n:name_badge:"     )
    super.RegisterSymbolX( 1, "🔰", "Japanese Symbol for Beginner`n:beginner:" )

    super.RegisterSymbolX( 1, "⬆️", "Up Arrow`n:arrow_up:"         )
    super.RegisterSymbolX( 1, "↗️", "Up-Right Arrow`n:arrow_upper_right:" )
    super.RegisterSymbolX( 1, "➡️", "Right Arrow`n:arrow_right:"   )
    super.RegisterSymbolX( 1, "↘️", "Down-Right Arrow`n:arrow_lower_right:" )
    super.RegisterSymbolX( 1, "⬇️", "Down Arrow`n:arrow_down:"     )
    super.RegisterSymbolX( 1, "↙️", "Down-Left Arrow`n:arrow_lower_left:" )
    super.RegisterSymbolX( 1, "⬅️", "Left Arrow`n:arrow_left:"     )
    super.RegisterSymbolX( 1, "↖️", "Up-Left Arrow`n:arrow_upper_left:" )
    super.RegisterSymbolX( 1, "↕️", "Up-Down Arrow`n:arrows_up_down:" )
    super.RegisterSymbolX( 1, "↔️", "Left-Right Arrow`n:arrows_left_right:" )
    super.RegisterSymbolX( 1, "↩️", "Right Arrow Curving Left`n:leftwards_arrow_with_hook:" )
    super.RegisterSymbolX( 1, "↪️", "Left Arrow Curving Right`n:arrow_right_hook:" )

    super.RegisterSymbolX( 1, "🔁", "Repeat Button`n:repeat:"      )
    super.RegisterSymbolX( 1, "🔂", "Repeat Single Button`n:repeat_one:" )
    super.RegisterSymbolX( 1, "🔀", "Shuffle`n:twisted_rightwards_arrows:" )
    super.RegisterSymbolX( 1, "🔃", "Clockwise Arrows`n:arrows_clockwise:" )
    super.RegisterSymbolX( 1, "♾️", "Infinity`n:infinity:"          )
    super.RegisterSymbolX( 1, "🆗", "OK Button`n:ok:"               )
    super.RegisterSymbolX( 1, "🆕", "NEW Button`n:new:"             )
    super.RegisterSymbolX( 1, "🆙", "UP Button`n:up:"               )
    super.RegisterSymbolX( 1, "🆒", "COOL Button`n:cool:"           )
    super.RegisterSymbolX( 1, "🆓", "FREE Button`n:free:"           )
    super.RegisterSymbolX( 1, "🆖", "NG Button`n:ng:"               )
    super.RegisterSymbolX( 1, "🔮", "Crystal Ball`n:crystal_ball:"  )
  }
}

